// ---------------------------------------------------------------------------
// /openapi.json — public, machine-readable spec for /v1/runs
// ---------------------------------------------------------------------------
//
// Serves `public/openapi.json` (auto-generated by `pnpm openapi:build`)
// from the App Router. This is the canonical public surface external
// SDKs and consumers bind to.
//
// Cache: public, max-age=300 — the spec is tied to the deployed Studio
// version (info.version comes from package.json), so a 5-min stale
// window is fine and friendly to Vercel's edge cache.
//
// Why we don't `fs.readFile` the absolute path: Next.js statically
// includes anything under `public/` in the deployment artifact, but the
// runtime working directory inside Vercel functions is not the project
// root. Inlining via static import keeps deploys deterministic and
// avoids surprises when the build cwd differs.
// ---------------------------------------------------------------------------

import { NextResponse } from "next/server";

// `resolveJsonModule` (tsconfig) is true; the JSON ships in the route
// bundle. The file is regenerated by `pnpm openapi:build` and committed.
import openapiSpec from "../../../public/openapi.json";

export const dynamic = "force-static";
export const revalidate = 300;

export function GET(): Response {
  return NextResponse.json(openapiSpec, {
    status: 200,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=300",
    },
  });
}
